### ISSUE TITLE
You Get Banned!!

### ISSUE THREAD

**Issue by Batapple** [ChiefChippy2/Vocab-Bot-V2#1]
As far as I am sure, you get banned when you use this so be careful and dont get banned!!!!!

**Comment by ChiefChippy2** [comment]
iirc only if you use it for a long time.

**Comment by Batapple** [comment]
I only used it for a minute and my account got deleted

**Comment by ChiefChippy2** [comment]
Fixed in latest release (v1.2.0). You might have to reset extension data by clicking on details -> extension options -> reset data.
