### ISSUE TITLE
It doesn't use all lists from the word you input?

### ISSUE THREAD

**Issue by rwrwrwrw** [ChiefChippy2/Vocab-Bot-V2#2]
It doesn't use all lists from the word you input?

**Comment by rwrwrwrw** [comment]
Can't find any words with enough lists to last for a long time

**Comment by rwrwrwrw** [comment]
is there a way to fix this in the code?

**Comment by ChiefChippy2** [comment]
try the keyword "test"


I suppose I can take a look to see how I can make this nonstop

**Comment by ChiefChippy2** [comment]
I added a "*" option to use rng list (basically tries a random number and see if a list with an id of that number exists)

lmk if it works (well)

**Comment by rwrwrwrw** [comment]
Worked well for a while, but then started to give me errors like "could not load resource (one of the random vocab lists)". I don't know if its something about my pc or if it may be a bug

**Comment by ChiefChippy2** [comment]
> Worked well for a while, but then started to give me errors like "could not load resource (one of the random vocab lists)". I don't know if its something about my pc or if it may be a bug

can you send a screenshot?

**Comment by rwrwrwrw** [comment]
![2021-09-05-121532_1920x1080_scrot](https://user-images.githubusercontent.com/90114199/132138777-a4365862-82b6-4a12-9756-47ff6767002e.png)

**Comment by ChiefChippy2** [comment]
yup patched that, vocaulary.com isn't a site

**Comment by rwrwrwrw** [comment]
I have a feeling it has something to do with me. Still getting the same error, and it says it has something to do with the backround page.

**Comment by ChiefChippy2** [comment]
> I have a feeling it has something to do with me. Still getting the same error, and it says it has something to do with the backround page.

did you download the latest version

**Comment by ChiefChippy2** [comment]
(and loaded it over the old version etc)

**Comment by rwrwrwrw** [comment]
yes, but ill try it again to make sure

**Comment by rwrwrwrw** [comment]
Still having the same problems

**Comment by ChiefChippy2** [comment]
try removing the extension then readding it. make sure you are downloading the master branch and not the release from a few months ago

**Comment by rwrwrwrw** [comment]
that worked but the only thing that doesn't is using the "*"

**Comment by rwrwrwrw** [comment]
i tried again, the function that searches for lists isn't working

**Comment by rwrwrwrw** [comment]
is there a way to fix it?

**Comment by ChiefChippy2** [comment]
fixed in latest release ( normally ).
