### ISSUE TITLE
Manifest V3

### ISSUE THREAD

**Issue by Smehlololol** [ChiefChippy2/Vocab-Bot-V2#3]
Google has upgraded to manifest v3 can you please upgrade it?
![Screenshot 2023-05-03 190233](https://user-images.githubusercontent.com/111461504/236094864-bb1928ef-d6b8-483c-a27b-2ea9acdb2d96.png)

**Comment by ChiefChippy2** [comment]
Released to v1.3.0
However I can't guarantee if this still functions, and maintenance on this repo is basically defunt
